remote_theme: just-the-docs/just-the-docs
title: CampusConnect Berlin
description: Projekt im Rahmen des Moduls Full Stack Web Development von Kaan Baskaya, Jan Busson und Ailin Esenalieva

mermaid:
  version: "10.5.0"

callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk
