title: CampusConnect Berlin
remote_theme: just-the-docs/just-the-docs@v0.6.2
plugins:
  - jekyll-remote-theme
  
mermaid:
  version: "10.9.0" # Pick version from https://cdn.jsdelivr.net/npm/mermaid/
callouts:
  tip:
    title: ğŸ¤ Tip
    color: purple
  info:
    title: â„¹ï¸ Info
    color: blue
  attention:
    title: â• Attention
    color: yellow
  download:
    title: ğŸ’¾ Download
    color: grey-dk